server:
  port: 9011
spring:
  application:
    name: tensquare-friend
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.25.133:3306/tensquare_friend?characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123
  jpa:
    database: mysql
    show-sql: true
jwt:
  ttl: 3600000
  key: zelin
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka/